version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: pasteinsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  pastebins:
    image: docker.io/library/pbin:0.1.0-SNAPSHOT
    environment:
      DB_URL: postgresdb
      DB_USER: postgres
      DB_PASS: pass1234
      DB_NAME: pasteinsdb
    ports:
      - "1234:1234"
    depends_on:
      - postgresdb
volumes:
  postgres:
